### ISSUE TITLE
Redraw references table in frontend after saving new reference

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/apis-bibsonomy#17]
Current state: 
When adding a new reference in the frontend tooltip form, the newly added reference doesn't show up in the references table after save. Only shows up if bibsonomy icon is clicked again and reloaded. 

Desired behaviour: 
Redraw reference table after save.

**Comment by gregorpirgie** [comment]
relates to #20

**Comment by b1rger** [comment]
we don't use tooltips anymore, the reference form was refactored -> closing
