### ISSUE TITLE
Clear form data after save

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/apis-bibsonomy#20]
Current behaviour: 

When saving new reference, as described in #17 , you must close the tooltip and click the bibsonomy icon again to see the newly added reference. But furthermore, even if you currently click the icon again, it also prefills all formfields with the data entered from the last created reference. 

Expected behaviour:

Form data should be cleared after succesfull save and newly added reference should show up in reference table (as described in issue #17.

**Comment by b1rger** [comment]
we don't use tooltips anymore, the reference form was refactored -> therefore closing
