### ISSUE TITLE
Add edit button in tooltip references table

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/apis-bibsonomy#22]
Current state:
Users can only delete existing references in the frontend forms.
So they need to delete and re-add the whole reference if they want to change anything. 

Desired feature: 
Add an additional column with an edit button, and implement logic to load the existing reference data into the form-fields to make them editable.

**Comment by b1rger** [comment]
There is now an edit view and it is linked from the reference listview df36657b05d32abd0c5da9910efbdad759ab57b7
